<%
username=session("fy_u_nickname")
if username<>"聊天室管理员" then  Response.Redirect "manerr.asp?id=230"
s1=Request.Form ("s1")
s2=Request.Form ("s2")
s4=Request.Form ("s4")
s5=Request.Form ("s5")
s6=Request.Form ("s6")
s7=Request.Form ("s7")
s8=Request.Form ("s8")
s9=Request.Form ("s9")
s10=Request.Form ("s10")
s11=Request.Form ("s11")
s12=Request.Form ("s12")
s13=Request.Form ("s13")
s14=Request.Form ("s14")
s15=Request.Form ("s15")
s16=Request.Form ("s16")
s17=Request.Form ("s17")
s19=Request.Form ("s19")
s20=Request.Form ("s20")
s21=Request.Form ("s21")
s22=Request.Form ("s22")
s23=Request.Form ("s23")
s24=Request.Form ("s24")
s25=Request.Form ("s25")
s26=Request.Form ("s26")
s27=Request.Form ("s27")
s28=Request.Form ("s28")
Set conn=Server.CreateObject("ADODB.CONNECTION")
Set rs=Server.CreateObject("ADODB.RecordSet")
conn.open Application("hg_connstr")
conn.Execute ("update system set chatroomname='"&s1&"',automanname='"&s2&"',disloginname='"&s4&"',userinto='"&s5&"',userout='"&s6&"',userdown='"&s7&"',logo='"&s8&"',opendate='"&s9&"',visitor='"&s10&"',maxpeople='"&s11&"',homepageurl='"&s12&"',maxtimeout='"&s13&"',iplocktime='"&s14&"',closedoor='"&s15&"',disproxy='"&s16&"',disnewuser='"&s17&"',chatroombgcolor='"&s19&"',chatroombgimage='"&s20&"',chatbgcolor='"&s21&"',chatimage='"&s22&"',chatcolor='"&s23&"',titlecolor='"&s24&"',level1to2='"&s25&"',level2to3='"&s26&"',level3to4='"&s27&"',level4to5='"&s28&"'")
rs.Open ("select * from system"),conn
Application("fy_c_chatroomname")=rs("chatroomname")
Application("fy_c_user")=rs("user")
Application("fy_c_sn")=rs("sn")
Application("fy_c_copyright")=rs("copyright")
Application("fy_c_visitor")=rs("visitor")
Application("fy_c_chatroombgimage")=rs("chatroombgimage")
Application("fy_c_homepageurl")=rs("homepageurl")
Application("fy_c_opendate")=rs("opendate")
Application("fy_c_chatroombgcolor")=rs("chatroombgcolor")
Application("fy_c_chatbgcolor")=rs("chatbgcolor")
Application("fy_c_chatimage")=rs("chatimage")
Application("fy_c_chatcolor")=rs("chatcolor")
Application("fy_c_logo")=rs("logo")
Application("fy_c_ver")=rs("ver")
Application("fy_c_allowhtml")=int(rs("allowhtml"))
Application("fy_c_iplocktime")=int(rs("iplocktime"))
Application("fy_c_level1to2")=int(rs("level1to2"))
Application("fy_c_level2to3")=int(rs("level2to3"))
Application("fy_c_level3to4")=int(rs("level3to4"))
Application("fy_c_level4to5")=int(rs("level4to5"))
Application("fy_c_maxpeople")=int(rs("maxpeople"))
Application("fy_c_maxtimeout")=int(rs("maxtimeout"))
Application("fy_c_pollbegin")=CDate(rs("pollbegin"))
Application("fy_c_pollend")=CDate(rs("pollend"))
Application("fy_c_pollvalue")=CDate(rs("pollvalue"))
Application("fy_c_disproxy")=rs("disproxy")
Application("fy_c_disnewuser")=rs("disnewuser")
Application("fy_c_titlecolor")=rs("titlecolor")
Application("fy_c_closedoor")=rs("closedoor")
Application("fy_c_automanname")=rs("automanname")
Application("fy_c_disloginname")=rs("disloginname")
Application("fy_c_userinto")=rs("userinto")
Application("fy_c_userout")=rs("userout")
Application("fy_c_userdown")=rs("userdown")
rs.Close
set rs=nothing
conn.Close
set conn=nothing
Response.Redirect "mansys.asp"
%>